# Site settings
title: Data Science Notes
email: mert.nuhoglu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Data science studies and notes
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://datascience.mertnuhoglu.com" # the base hostname & protocol for your site
twitter_username: mertnuhoglu
github_username:  mertnuhoglu

# Build settings
markdown: kramdown

analytics :
provider : google 
google : 
    tracking_id : 'UA-20351819-8'
